# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

target 'GitRepoFind' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitRepoFind
  pod 'ProgressHUD'
  pod 'RxAlamofire'
  pod 'Kingfisher'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  
  target 'GitRepoFindTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.name == 'Test'
                config.build_settings['ENABLE_TESTABILITY'] = 'YES'
            end
        end
    end
end
