# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

target 'GitRepoFind' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitRepoFind
  pod 'UIScrollView-InfiniteScroll'
  pod 'ProgressHUD'
  pod 'RxAlamofire'
  pod 'Kingfisher'
  pod 'RxSwift'
  pod 'RxCocoa'
  
  target 'GitRepoFindTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
